name: Build AetherSpigot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Run Gradle
        run: ./gradlew build
